matrix: #allows to set up tests/deploys in different languages/environments.
  include: #includes all stages of build
    - stage: deploy # this block builds and deploys the docs, it's in Python.
      language: python
      sudo: required
      dist: trusty
      install:
        - sudo apt-get install jq
        - pip install mkdocs==1
        - pip install mkdocs-material==3.0.3
      script:
        - mkdir docs/styles
        - mkdir docs/images
        - curl https://api.github.com/repos/compbiocore/cbc-documentation-templates/contents/files/dark_mode.css\?access_token\=$GITHUB_TOKEN > dark_mode.json
        - jq -r '.content' < dark_mode.json | base64 --decode > docs/styles/dark_mode.css
        - curl https://api.github.com/repos/compbiocore/cbc-documentation-templates/contents/files/cbc-logo.svg\?access_token\=$GITHUB_TOKEN > logo.json
        - jq -r '.content' < logo.json | base64 --decode > docs/images/cbc-logo.svg
        - mkdocs build --verbose --clean --strict
      deploy:
       provider: pages
       skip_cleanup: true
       github_token: $GITHUB_TOKEN
       local_dir: site
       on:
         branch: master
