site_name:        Software Development Best Practices
site_author:      Fernando Gelin
repo_url:         https://github.com/compbiocore/cbc-documentation-templates
site_description: Documentation templates and best-practices for Brown's Computational Biology Core.
site_url: https://compbiocore.github.io/

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: images/cbc-logo.svg

extra_css:
  - styles/dark_mode.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
  - footnotes

nav:
  - Home: 'index.md'
  - Documentation:
      - MkDocs and Travis: 'mkdocs.md'
      - Set up for CD: 'index_site.md'
      - Templates: 'readme.md'
